apiVersion: v1
kind: Service
metadata:
  name: oart-decoder-svc
  namespace: default
  labels:
    app: oart-decoder
spec:
  selector:
    app: oart-decoder
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 30005
    targetPort: 30005
    name: beast
  - port: 30003
    targetPort: 30003
    name: sbs
  type: ClusterIP
